version: "3.8"

services:
    develop:
        image: webfolio_service_name
        ports:
            - 3000:3000
        volumes:
            - ./client:/app
            - /app/node_modules
        working_dir: /app
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
    
    build:
        image: webfolio_service_name
        ports:
            - 80:80
        volumes:
            - ./client:/app
            - /app/node_modules
        working_dir: /app
        stdin_open: true
        command: yarn build && serve -s build
        